Worker: fix issue with Task retcode handling when there is no rc
Obviously, only command-based Workers do provide a return code. Avoid
propagating rc=None to the Task. Renamed Worker._on_rc() and other
similar methods to Worker._on_close() to avoid confusion. Keep
Task._set_rc() that is now only called when a valid retcode is
available.

Issue revealed by the Python 3 porting effort in tree mode. Triggers a
TypeError exception in Python 3 only:

  File "lib/ClusterShell/Task.py", line 1039, in _rc_set
      if self._max_rc is None or rc > self._max_rc:
      TypeError: unorderable types: NoneType() > int()

Indeed the issue is not seen in Python 2 because the comparison between
None and integers is supported.

Added specific non-reg test that requires at least a StreamWorker and a
command-based worker like ExecWorker.

Change-Id: Ie165b5221e91efafb245c2f1ee7a071972e28ad4